site_name: FreeSIEM
theme:
  name: material
# 仓库链接
repo_url: https://github.com/h4m5t/FreeSIEM.git
# 作者
site_author: 'h4m5t'
# 版权信息
copyright: '2023, h4m5t'
# 源文件目录
docs_dir: 'docs'
# 生成静态文件目录
# site_dir: 'site'
# 额外信息
extra:
    # 版本号
    version: 1.0
# markdown扩展
markdown_extensions:

# 导航
nav:
    - Home: index.md
