site_name: FreeSIEM
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.footer
    - navigation.top # 一键回顶部

  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: white
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: grey
      toggle:
        icon: material/weather-night
        name: Switch to light mode


# 仓库链接
repo_url: https://github.com/h4m5t/FreeSIEM
repo_name: h4m5t/FreeSIEM
# 作者
site_author: 'h4m5t'
# 版权信息
copyright: Copyright &copy; 2023 h4m5t
# 源文件目录
docs_dir: 'docs'
# 生成静态文件目录
# site_dir: 'site'
# 额外信息
extra:
    # 版本号
    version: 1.0
    social:
    - icon: fontawesome/brands/zhihu
      link: https://www.zhihu.com/people/h4m5t
    - icon: fontawesome/brands/github
      link: https://github.com/h4m5t
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/h4m5t
    - icon: fontawesome/brands/medium
      link: https://medium.com/@h4m5t

# markdown扩展
markdown_extensions:

# 导航
nav:
    - Home: index.md
      - 文档汇总: all_doc.md
    - Getting started:
      - Installation: install.md
      - 安装thehive4: install_thehive4.md
      - 安装thehive5: install_thehive5.md
      - 安装shuffle: install_shuffle.md
      - 安装MISP: install_MISP.md
      - 安装TheHive+MISP: install_thehivemisp.md
      - 安装wazuh: install_wazuh.md
      - 安装SecurityOnion: install_SO2.3.md
      - 安装KaliPurple: install_kalipurple.md
      - 磁盘扩容: cipankuorong.md
      - 学习视频: learnshipin.md
    - Reference:
      - Reference: reference.md
